- name: Install dependencies
  community.general.pacman:
    state: present
    name:
      - hypridle
      - brightnessctl

- name: Create hypr folder
  ansible.builtin.file:
    path: "{{ play_user_config_dir }}/hypr"
    state: directory
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
    mode: "{{ perm_folders }}"

- name: Copy over hypridle config
  ansible.builtin.copy:
    src: hypridle.conf
    dest: "{{ play_user_config_dir }}/hypr/hypridle.conf"
    mode: "{{ perm_files }}"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
