- name: Install packages
  community.general.pacman:
    state: present
    update_cache: true
    name: "{{ devel_packages }}"

- name: Create aur_builder user
  ansible.builtin.include_tasks: aur_builder.yml

- name: Install aur packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    update_cache: true
    name: "{{ devel_packages_aur }}"
    use: yay
    aur_only: true
