- name: Copy ozone flags to config
  ansible.builtin.copy:
    src: electron-flags.conf
    dest: "{{ play_user_config_dir }}/electron-flags.conf"
    mode: "{{ perm_files }}"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"

- name: Disable x11 in all flatpaks and enable wayland
  changed_when: true
  ansible.builtin.command:
    cmd: |
      flatpak override --user
      --socket=wayland
      --nosocket=x11
      --nosocket=fallback-x11
