- name: Install flatpak itself
  community.general.pacman:
    state: present
    name: flatpak

- name: Remove system-wide remote (flathub)
  community.general.flatpak_remote:
    name: flathub
    state: absent
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Enable user-wide remote (flathub)
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
    enabled: true
