- name: Install Breeze for flatpak
  become: true
  become_user: "{{ play_user }}"
  community.general.flatpak:
    state: present
    name: org.gtk.Gtk3theme.Breeze
    method: user

- name: Add global read only paths for theming
  become: true
  become_user: "{{ play_user }}"
  ansible.builtin.command:
    cmd: |
      flatpak override --user
      --filesystem=~/.themes:ro
      --filesystem=~/.icons:ro
      --filesystem=~/.local/share/themes:ro
      --env=GTK_THEME=Breeze-Dark
      --env=ICON_THEME=Breeze-Dark
  changed_when: true
