- name: Create qt5ct folder
  ansible.builtin.file:
    state: directory
    dest: "{{ play_user_config_dir }}/qt5ct"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
    mode: "755"

- name: Copy qt5 config
  ansible.builtin.copy:
    src: qt5ct.conf
    dest: "{{ play_user_config_dir }}/qt5ct/qt5ct.conf"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
    mode: "644"

- name: Create qt6ct folder
  ansible.builtin.file:
    state: directory
    dest: "{{ play_user_config_dir }}/qt6ct"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
    mode: "755"

- name: Copy qt6 config
  ansible.builtin.copy:
    src: qt6ct.conf
    dest: "{{ play_user_config_dir }}/qt6ct/qt6ct.conf"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
    mode: "644"
