- name: Install xdg-user-dirs
  community.general.pacman:
    state: present
    name: xdg-user-dirs

- name: Copy dirs config
  ansible.builtin.copy:
    src: user-dirs.dirs
    dest: "{{ play_user_config_dir }}/user-dirs.dirs"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
    mode: "644"
