- name: Install hyprlock
  community.general.pacman:
    name: hyprlock

- name: Copy compose file
  ansible.builtin.copy:
    src: hyprlock.conf
    dest: "{{ play_user_config_dir }}/hypr/hyprlock.conf"
    mode: "{{ perm_files }}"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"

- name: Create assets folder
  ansible.builtin.file:
    path: "{{ play_user_config_dir }}/hypr/assets"
    state: directory
    mode: "{{ perm_folders }}"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"

- name: Copy assets
  ansible.builtin.copy:
    src: "assets/{{ item }}"
    dest: "{{ play_user_config_dir }}/hypr/assets/{{ item }}"
    mode: "{{ perm_files }}"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
  loop:
    - background.png
    - profile.png
    - distro.png
