pkg_pacman:
  - nano
  - helix
  - eza
  - dust
  - imagemagick
  - man-db
  - 7zip
  - unzip
  - bind
  - jq
  - fastfetch
  - kitty
  - rsync
  - yt-dlp
  - pavucontrol
  - pamixer
  - networkmanager
  - network-manager-applet
  - nextcloud-client
  - gst-plugin-pipewire
  - wireplumber
  - parallel
  - brightnessctl
  - udiskie
  - archlinux-xdg-menu
  - cliphist
  - wl-clipboard
  - inetutils
  - ffmpeg
  - qt5-wayland
  - qt6-wayland
  - zed
  - ansible
  - ansible-lint

pkg_aur:
  - etcher-bin
  - vscodium-bin
  - vscodium-bin-marketplace
  - vscodium-xdg-dir-patch

pkg_flatpak:
  - app.zen_browser.zen
  - com.github.tchx84.Flatseal
  - eu.betterbird.Betterbird
  - com.discordapp.Discord
  - com.usebruno.Bruno
