- name: Install all dotfiles
  become: true
  hosts: all
  vars_files:
    - ../vars/env.yml
    - ../vars/theme.yml
  roles:
    - basics
    - devel
    - xdg
    - flatpak
    - dolphin
    - dunst
    - fish
    - fonts
    - grub
    - hypridle
    - hyprland
    - hyprlock
    - kwallet
    - locale
    - nvidia
    - polkit
    - rofi
    - screenshot
    - scripts
    - searxng
    - waybar
    - wayland
    - theme
    - pkg
    - wakeonlan
